# Generated by Django 4.1.6 on 2023-02-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="lineup", name="type",),
        migrations.AddField(
            model_name="goals",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="lineup",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_lineups",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="matchcards",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="missedpenalty",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missed_penalties",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitutions",
                to="teams.team",
            ),
        ),
    ]
