# Generated by Django 4.1.6 on 2023-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_lineup_type_goals_team_lineup_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gameweek',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
