# Generated by Django 4.1.6 on 2023-02-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stadiums", "0001_initial"),
        ("coaches", "0001_initial"),
        ("regions", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "departure_reason",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Sacked"), (2, "Mutual Consent")],
                        null=True,
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coaches.coach"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "shirt_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="regions.city",
                    ),
                ),
                (
                    "coaches",
                    models.ManyToManyField(
                        related_name="teams",
                        through="teams.CoachList",
                        to="coaches.coach",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="teams",
                        through="teams.PlayerList",
                        to="players.player",
                    ),
                ),
                (
                    "stadium",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stadiums.stadium",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playerlist",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="coachlist",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
    ]
