# Generated by Django 4.1.6 on 2023-02-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stadiums", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="stadium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stadiums.stadium"
            ),
        ),
    ]
