# Generated by Django 4.1.6 on 2023-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_playerlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Permanent'), (2, 'On Loan'), (3, 'Youth')], default=1),
        ),
    ]
