# Generated by Django 4.1.6 on 2023-02-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "nationality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.country",
                    ),
                ),
            ],
        ),
    ]
