# Generated by Django 4.1.6 on 2023-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Kabupaten"), (2, "Kota")], null=True
            ),
        ),
    ]
