# Generated by Django 4.1.6 on 2023-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_playerlist_status'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participated_teams',
            field=models.ManyToManyField(related_name='competitions', to='teams.team'),
        ),
    ]
