# Generated by Django 4.1.6 on 2023-02-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "abbreviation",
                    models.CharField(db_index=True, max_length=3, unique=True),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Forward"),
                            (2, "Midfielder"),
                            (3, "Defender"),
                            (4, "Goalkeeper"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "preferred_foot",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "Left"), (2, "Right")], null=True
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.country",
                    ),
                ),
                (
                    "other_position",
                    models.ManyToManyField(
                        related_name="other_position_players", to="players.position"
                    ),
                ),
                (
                    "primary_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_position_players",
                        to="players.position",
                    ),
                ),
            ],
        ),
    ]
