# Generated by Django 4.1.6 on 2023-02-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0002_city_type"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="place_of_birth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="regions.city",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Permanent"), (2, "On Loan")], default=1
            ),
        ),
    ]
