# Generated by Django 4.1.6 on 2023-02-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_player_citizenship_player_place_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fullname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="other_position",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="other_position_players",
                to="players.position",
            ),
        ),
    ]
