# Generated by Django 4.1.6 on 2023-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_fullname_alter_player_other_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
