# Generated by Django 4.1.6 on 2023-02-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_position_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='status',
        ),
    ]
